name: Release action
description: Releases an action in a consistent way to be used across action repos
inputs:
  github-token:
    description: The github token used to push release tags
    required: true
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: "0"
    - name: Bump version and push tag
      id: bump-version
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        RELEASE_BRANCHES: feat-major-tag-test
        WITH_V: true
    - name: Update major and minor level tags
      uses: sersoft-gmbh/running-release-tags-action@v2
      with:
        tag: ${{ steps.bump-version.outputs.new_tag }}
        create-release: false
